CREATE TABLE PERSONNES(
idPersonne INT PRIMARY KEY IDENTITY(1,1),
nom VARCHAR(64) NOT NULL,
prenom VARCHAR(64) NOT NULL,
noRue INT NOT NULL,
rue VARCHAR(64) NOT NULL,
cp INT NOT NULL,
ville VARCHAR(64) NOT NULL,
CONSTRAINT CK_CP CHECK (cp BETWEEN 0 AND 96000)
);

CREATE TABLE VEHICULES(
immatriculation VARCHAR(64) PRIMARY KEY NOT NULL,
marque VARCHAR(64) NOT NULL,
Kilometrage DECIMAL(9,3) NOT NULL,
DateMiseEnService DATE NOT NULL,
proprietaire INT NOT NULL,
CONSTRAINT FK_Proprio FOREIGN KEY (proprietaire) REFERENCES PERSONNES(idPersonne)
);
