CREATE TABLE ETUDIANTS_1(
IdEtudiant INT PRIMARY KEY NOT NULL,
Nom VARCHAR(50) NOT NULL,
Prenom VARCHAR(50) NOT NULL,
DateEntree DATE NOT NULL 
) ;
CREATE TABLE MATIERES_1(
IdMatiere INT PRIMARY KEY NOT NULL,
LblMatiere VARCHAR(50) NOT NULL,
Coefficient INT NOT NULL,
CONSTRAINT cle_LblMatiere UNIQUE(LblMAtiere)
) ;
CREATE TABLE CONTROLER_1(
IdEtudiant INT  NOT NULL,
IdMatiere INT NOT NULL,
moyenne decimal(4,2),
CONSTRAINT FK_ETUD FOREIGN KEY (IdEtudiant) REFERENCES ETUDIANTS_1(IdEtudiant),
CONSTRAINT FK_MAT FOREIGN KEY (IdMatiere) REFERENCES MATIERES_1(IdMatiere),
CONSTRAINT PK_ETUDIANT PRIMARY KEY (IdEtudiant,IdMatiere)
);
