CREATE TABLE RAYONS(
nomR VARCHAR(30) PRIMARY KEY NOT NULL
);
CREATE TABLE ARTICLES(
codeA INT PRIMARY KEY IDENTITY NOT NULL,
nomA VARCHAR(50) NOT NULL,
typeA VARCHAR(50) NOT NULL,
CONSTRAINT CK_TYPE CHECK (typeA IN('P:papeterie','L:livre','D:disque'))
);
CREATE TABLE MAGASIN(
codeM INT PRIMARY KEY NOT NULL,
nomM CHAR(30) NOT NULL 
);
CREATE TABLE VENDRE(
quantiteS VARCHAR(30) NOT NULL,
nomR VARCHAR(30),
codeA INT,
codeM INT,
CONSTRAINT FK_nomR FOREIGN KEY (nomR) REFERENCES RAYONS(nomR),
CONSTRAINT FK_codeA FOREIGN KEY (codeA) REFERENCES ARTICLES(codeA),
CONSTRAINT FK_codeM FOREIGN KEY (codeM) REFERENCES MAGASIN (codeM),
CONSTRAINT PK_KEY PRIMARY KEY(codeM, nomR, codeA)
);