CREATE TABLE FOURNISSEURS_exo6(
codeF INT PRIMARY KEY NOT NULL,
adresseF VARCHAR(50) NOT NULL,
nomF VARCHAR(50) NOT NULL
);
CREATE TABLE RAYONS_exo6(
nomR2 VARCHAR(50) PRIMARY KEY NOT NULL,
etageR INT NOT NULL
);
CREATE TABLE EMPLOYES_exo6(
codeE INT PRIMARY KEY NOT NULL,
nomE VARCHAR(50) NOT NULL,
salaireE DECIMAL(9,2) NOT NULL,
nomR2 VARCHAR(50),
codeE_chef INT,
CONSTRAINT FK_nomR2  FOREIGN KEY (nomR2) REFERENCES RAYONS_exo6(nomR2),
CONSTRAINT FK_cod_chef FOREIGN KEY (codeE_chef) REFERENCES EMPLOYES_exo6(codeE)
);
CREATE TABLE ARTICLES_exo6(
codeA2 INT PRIMARY KEY NOT NULL,
nomR2 VARCHAR(50),
nomA2 VARCHAR(50) NOT NULL,
typeA VARCHAR(50) NOT NULL,
CONSTRAINT FK_nomRayon FOREIGN KEY (nomR2) REFERENCES RAYONS_exo6(nomR2),
);
CREATE TABLE LIVRER_exo6(
quantite INT NOT NULL,
codeF INT,
codeA2 INT,
CONSTRAINT FK_codeF FOREIGN KEY (codeF) REFERENCES FOURNISSEURS_exo6(codeF),
CONSTRAINT FK_codeA2 FOREIGN KEY (codeA2) REFERENCES ARTICLES_exo6(codeA2),
CONSTRAINT PK_LIV PRIMARY KEY(codeF, codeA2)
);
CREATE INDEX idxEmploy ON EMPLOYES_exo6(nomE)
CREATE INDEX IDXtYPE ON ARTICLES_exo6(typeA)