CREATE TABLE BUVEURS(
numBuv INT PRIMARY KEY NOT NULL,
nomBuv VARCHAR(50) NOT NULL,
prenomBuv VARCHAR(50) NOT NULL,
villeBuv VARCHAR(50) NOT NULL,
CONSTRAINT cle_U UNIQUE (nomBuv,prenomBuv)
);
CREATE TABLE COMMANDES(
numCom INT NOT NULL,
numBuv INTEGER,
dateCom DATETIME NOT NULL,
CONSTRAINT FK_NUMBUV FOREIGN KEY (numBuv) REFERENCES BUVEURS(numBuv),
CONSTRAINT PK_nomCom PRIMARY KEY(numCom)
);
CREATE TABLE VIGNERONS(
numVig INT PRIMARY KEY NOT NULL,
nomVig VARCHAR(50) NOT NULL,
prenomVig VARCHAR(50) NOT NULL,
villeVig VARCHAR(50),
);
CREATE TABLE VINS(
numVin INTEGER PRIMARY KEY NOT NULL,
cru VARCHAR(50) NOT NULL,
milesime VARCHAR(50) NOT NULL,
numVig INT NOT NULL,
CONSTRAINT FK_numVig FOREIGN KEY (numVig) REFERENCES VIGNERONS(numVig)
);
CREATE TABLE ACHETER(
quantite INT NOT NULL,
numVin INT NOT NULL,
numCom int NOT NULL,
CONSTRAINT FK_numVin FOREIGN KEY (numVin) REFERENCES VINS(numVin)
);
CREATE TABLE CRITERE(
numVig_apprecier INT NOT NULL,
numVig_etreapprecier INT NOT NULL,
numVig INT NOT NULL,
CONSTRAINT FK_apprecier FOREIGN KEY (numVig_apprecier) REFERENCES VIGNERONS (numVig),
CONSTRAINT FK_etreapprecier FOREIGN KEY (numVig_etreapprecier) REFERENCES VIGNERONS (numVig)
);

