CREATE TABLE DEPT(
DEPTNO INT PRIMARY KEY IDENTITY (10,10) NOT NULL,
DNAME VARCHAR(30) NOT NULL,
LOC VARCHAR(30) NOT NULL
);

SELECT * FROM DEPT

INSERT INTO DEPT
VALUES
('ACCOUNTING','NEW YORK'),
('RESEARCH','DALLAS'),
('SALES','CHICAGO'),
('OPERATIONS','BOSTON')
; 

SELECT * FROM DEPT

CREATE TABLE EMP(
EMPNO INT PRIMARY KEY NOT NULL,
ENAME VARCHAR(30) NOT NULL,
JOB VARCHAR(30) NOT NULL,
MGR INT,
HIREDATE DATE NOT NULL,
SAL INT NOT NULL,
COMM INT,
DEPTNO INT NOT NULL,
CONSTRAINT FK_DEPTNO FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO)
);

SELECT * FROM EMP

INSERT INTO EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) 
VALUES
(7369,'SMITH','CLERK',7902,'19801217',800,null,20),
(7499,'ALLEN','SALESMAN',7698,'19810220',1600,300,30),
(7521,'WARD','SALESMAN',7698,'19810222',1250,500,30),
(7566,'JONES','MANAGER',7839,'19810402',2975,null,20),
(7654,'MARTIN','SALESMAN',7698,'19810928',1250,1400,30),
(7698,'BLAKE','MANAGER',7839,'19810501',2850,null,30),
(7782,'CLARK','MANAGER',7839,'19810609',2450,null,10),
(7788,'SCOTT','ANALYST',7566,'19821209',3000,null,20),
(7839,'KING','PRESIDENT',null,'19811117',5000,null,10),
(7844,'TURNER','SALESMAN',7698,'19810908',1500,0,30),
(7876,'ADAMS','CLERK',7788,'19830112',1100,null,20),
(7900,'JAMES','CLERK',7698,'19811203',950,null,30),
(7902,'FORD','ANALYST',7566,'19811203',3000,null,20),
(7934,'MILLER','CLERK',7782,'19820123',1300,null,10);

SELECT * FROM EMP 



/*1*/SELECT ENAME, JOB,EMPNO,SAL 
FROM EMP 
WHERE DEPTNO=10

/*2*/SELECT ENAME,JOB,SAL 
FROM EMP 
WHERE SAL>2800 AND SOUNDEX (JOB) = SOUNDEX('MANAGEUR')

/*3*/SELECT * 
FROM EMP 
WHERE DEPTNO <>30

/*4*/SELECT * 
FROM EMP 
WHERE SAL BETWEEN 1200 AND 1400
 
/*5*/SELECT * 
FROM EMP 
WHERE DEPTNO IN (10,30) 
ORDER BY ENAME ASC;

/*6*/SELECT * 
FROM EMP 
WHERE DEPTNO=30 
ORDER BY SAL ASC;

/*7*/SELECT * 
FROM EMP 
ORDER BY JOB DESC, SAL DESC; 

/*8*/SELECT JOB 
FROM EMP GROUP BY JOB

/*8 BIS*/SELECT DISTINCT JOB, 
COUNT (ENAME) AS EFFECTIF 
FROM EMP 
GROUP BY JOB; /*REQUETE ++*/

/*9*/SELECT EMP.DEPTNO, DEPT.DNAME 
FROM EMP INNER JOIN DEPT 
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE EMP.ENAME='ALLEN' 

/*10*/SELECT EMP.ENAME, DEPT.DNAME, EMP.JOB, EMP.SAL 
FROM EMP INNER JOIN DEPT 
ON EMP.DEPTNO=DEPT.DEPTNO 
ORDER BY EMP.DEPTNO DESC, EMP.SAL DESC;

/*11*/SELECT EMP.ENAME, EMP.SAL,EMP.COMM, (EMP.SAL+EMP.COMM)as'SAL+COMM' 
FROM EMP 
WHERE JOB='SALESMAN' 

/*SELECT FORMAT(GETDATE(),'ddd dd MMM yyyy')as date*/

/*12*/SELECT EMP.ENAME, EMP.JOB, 
FORMAT(HIREDATE,'ddd dd MMM yyyy')as DATE 
FROM EMP
WHERE DEPTNO=20

/*13*/SELECT DEPT.DEPTNO,DEPT.DNAME, 
MAX(SAL)AS SAL_ELEVE
FROM EMP INNER JOIN DEPT 
ON EMP.DEPTNO=DEPT.DEPTNO 
GROUP BY DEPT.DEPTNO,DEPT.DNAME

/*14*/
SELECT DEPT.DNAME,
SUM(EMP.SAL) as SALAIRE, 
COUNT(EMP.EMPNO) as NOMBRE_EMP,
AVG(EMP.SAL) as SAL_MOYEN
FROM EMP Right JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DEPT.DNAME


/*15*/SELECT DEPT.DEPTNO, DEPT.DNAME,
SUM(EMP.SAL) as SALAIRE, 
COUNT(EMP.EMPNO) as NOMBRE_EMP, 
/*SUM(EMP.SAL)/COUNT(EMP.EMPNO) as Moyen*/
AVG(SAL) as MOYENNE
FROM EMP 
INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO 
GROUP BY DEPT.DEPTNO , DEPT.DNAME HAVING COUNT(EMP.EMPNO) > 3


/*16*/SELECT ENAME, DEPTNO, SAL ,JOB
FROM EMP 
WHERE JOB IN (SELECT JOB from EMP WHERE ENAME = 'JONES') AND ENAME <> 'JONES' 


/*17*/SELECT ENAME,(SELECT AVG(SAL) FROM EMP) as [SALAIRE MOYEN] ,SAL 
FROM EMP 
WHERE SAL>(SELECT AVG(SAL)FROM EMP)

/*18*/
CREATE TABLE PROJET(
numP INT PRIMARY KEY IDENTITY(101,1) NOT NULL,
nomP CHAR(5) NOT NULL,
buget INT NOT NULL
);

INSERT INTO PROJET(nomP,buget)
VALUES
('ALPHA',96000),
('BETA',82000),
('GAMMA',15000);

SELECT * FROM PROJET

/*19*/
ALTER TABLE EMP 
ADD numP int;

ALTER TABLE EMP 
ADD CONSTRAINT FK_numP 
FOREIGN KEY (numP)
REFERENCES PROJET(numP)

UPDATE EMP
SET numP = 101
WHERE EMP.JOB='SALESMAN' AND EMP.DEPTNO = 30;

UPDATE EMP
SET numP = 102
WHERE EMP.DEPTNO <> 30 OR (EMP.DEPTNO=30 AND JOB <> 'SALESMAN')

TRUNCATE TABLE EMP

SELECT * FROM EMP

/*20*/
CREATE VIEW VUE_EMP
AS 
SELECT 
EMP.ENAME, EMP.JOB, DEPT.DNAME, PROJET.nomP
FROM EMP,DEPT,PROJET

/*21*/
SELECT ENAME,JOB,DNAME,nomP
FROM VUE_EMP
order by DNAME asc, nomP 

/*22*/
SELECT ENAME,JOB,PROJET.nomP
FROM EMP INNER JOIN PROJET
ON EMP.numP=PROJET.numP
WHERE JOB='MANAGER'
GROUP BY ENAME,JOB,PROJET.nomP

/*DEUXIEME PARTIE*/
/*1*/
SELECT *
FROM EMP 
WHERE  DEPTNO IN(20,30) AND JOB='MANAGER'

/*2*/
SELECT *
FROM EMP
WHERE JOB <> 'MANAGER' AND 
format (HIREDATE,'yy') =81

/*3*/
SELECT *
FROM EMP
WHERE COMM is not null and COMM <> 0;

/*4*/
SELECT ENAME, DEPTNO, JOB, HIREDATE
FROM EMP
ORDER BY DEPTNO DESC,JOB DESC,HIREDATE DESC;

/*5*/
SELECT *
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE DEPT.LOC='DALLAS'

SELECT *
FROM EMP
ORDER BY DEPTNO

/*6*/
SELECT EMP.ENAME, EMP.HIREDATE
FROM EMP
WHERE 
EMP.HIREDATE < ANY (SELECT HIREDATE FROM EMP WHERE JOB ='MANAGER')


SELECT E.ENAME, E.HIREDATE, M.ENAME, M.HIREDATE
FROM EMP E, EMP M
WHERE E.MGR=M.EMPNO AND E.HIREDATE < M.HIREDATE AND 
E.EMPNO NOT IN (SELECT DISTINCT EMP.MGR FROM EMP WHERE EMP.MGR IS NOT NULL)
ORDER BY E.DEPTNO;


/*7*/
select ENAME,JOB,MGR
FROM EMP 
WHERE EMPNO NOT IN (SELECT DISTINCT MGR FROM EMP WHERE MGR IS NOT NULL)


/*8*/
SELECT *
FROM EMP
WHERE 
HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME ='BLAKE')

/*9*/
SELECT *
FROM EMP
WHERE 
HIREDATE = (SELECT HIREDATE FROM EMP WHERE ENAME ='FORD')


/*10*/
SELECT *
FROM EMP
WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME ='CLARK')
AND ENAME <> 'CLARK'

/*11*/
SELECT *
FROM EMP
WHERE JOB = ANY (SELECT JOB FROM EMP WHERE ENAME ='TURNER')	AND ENAME <>'TURNER'

/*12*/
SELECT *
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE (DEPT.DNAME='RESEARCH ' or DEPT.DNAME='SALES') 
and HIREDATE = ANY 
(SELECT DISTINCT HIREDATE 
FROM EMP 
WHERE DEPT.DNAME='RESEARCH ' OR  DEPT.DNAME='SALES')


/*13*/
SELECT ENAME, HIREDATE,
FORMAT(HIREDATE,'dddd')as 'NOM DU JOUR'
FROM EMP


SELECT ENAME, HIREDATE,
FORMAT(HIREDATE,'dddd'),
format(getdate(),'ddd dd MMM yyyy')
FROM EMP

/*14*/
SELECT ENAME,JOB, DATEDIFF(MONTH,HIREDATE,getdate() )as 'Nombre de Mois '
FROM EMP

/*15*/
SELECT *
FROM EMP
WHERE (ENAME LIKE '%A%') AND (ENAME LIKE'%M%')
ORDER BY ENAME

/*16*/
SELECT *
FROM EMP
WHERE (ENAME LIKE '%A%%A%')

/*17*/
select *
from emp
where HIREDATE < any(select TOP 1 HIREDATE from emp where DEPTNO=10
order by HIREDATE)
ORDER BY HIREDATE;


/*18*/
SELECT TOP 1 JOB,
AVG(SAL) as [sal moy plus faible]
FROM EMP
group by JOB
order by [sal moy plus faible] asc;

SELECT TOP 1 JOB,
AVG(SAL) as [sal moy plus élevés]
FROM EMP
group by JOB
order by [sal moy plus élevés] desc;

/*19*/
SELECT top 1 DEPT.DEPTNO,
COUNT(EMP.EMPNO) as NOMBRE_EMP
FROM EMP INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DEPT.DEPTNO 
order by NOMBRE_EMP desc;


/*20*/
SELECT DEPT.DEPTNO, DEPT.DNAME,
cast(count(EMP.EMPNO)*100/
cast((select count(*)from emp) as decimal(10,2))as decimal(10,2)) 
as 'Répartition en %'
FROM EMP INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DEPT.DEPTNO,DEPT.DNAME;
