CREATE TABLE TYPEVICTIMES(
TYPEVICT_ID CHAR(50) PRIMARY KEY NOT NULL,
TYPEVICT_NOM CHAR(50) NOT NULL,
CONSTRAINT CK_TYPEVICT_NOM CHECK (TYPEVICT_NOM IN('entreprise','association','particulair','administration'))
);
CREATE TABLE EXPLOITATIONS(
EXPLOITATION_ID CHAR(32) PRIMARY KEY NOT NULL,
EXPLOITATION_NOM CHAR(32)
);
CREATE TABLE OBJETS(
OBJ_ID CHAR(50) PRIMARY KEY NOT NULL,
OBJ_TYPE CHAR(50) NOT NULL
);
CREATE TABLE SERVICES_COM(
SERV_ID CHAR(32) PRIMARY KEY NOT NULL,
SERV_NOM CHAR(32) NOT NULL
);
CREATE TABLE SECTEURS(
SECT_ID CHAR(50) PRIMARY KEY NOT NULL,
SECT_NOM CHAR(50) NOT NULL,
SERV_ID CHAR(32) NOT NULL,
CONSTRAINT FK_SERV FOREIGN KEY (SERV_ID) REFERENCES SERVICES_COM(SERV_ID)
);
CREATE TABLE FONCTIONNAIRES(
FCT_ID CHAR(32) PRIMARY KEY NOT NULL,
FCT_NOM CHAR(50) NOT NULL,
SERV_ID CHAR(32) NOT NULL,
CONSTRAINT FK_SERV_FCT FOREIGN KEY(SERV_ID) REFERENCES SERVICES_COM(SERV_ID)
);
CREATE TABLE INFRACTIONS(
INFR_ID INT PRIMARY KEY NOT NULL IDENTITY,
INFR_NOM CHAR(32) NOT NULL
);
CREATE TABLE AUTREINFRACTIONS(
AINFR_ID CHAR(50) PRIMARY KEY NOT NULL,
AINFR_NOM CHAR(50) NOT NULL
);
CREATE TABLE AFFAIRES(
AFF_ID CHAR(50) PRIMARY KEY NOT NULL,
AFF_NUM INT NOT NULL CHECK (AFF_NUM >=0),
AFF_DATE CHAR(50) NOT NULL,
AFF_NBPREL int NULL
DEFAULT 0,
AFF_NBPRELFAM int NULL
DEFAULT 0,
AFF_TRANSMSIRIJ int NULL
DEFAULT 0,
AFF_NBTIDENTIF int NULL
DEFAULT 0,
AFF_NBIIDENTIF int NULL
DEFAULT 0,
AFF_TYPEADN tinyint NOT NULL
DEFAULT 1,
AFF_TYPEPAP tinyint NOT NULL
DEFAULT 0,
AFF_DATCONSTAT char(50) NULL ,
AFF_DRSIRIJ char(50) NULL,
OBJ_ID CHAR(50) NOT NULL,
FCT_ID CHAR(32) NOT NULL,
INFR_ID INT NULL,
AINFR_ID CHAR(50) NULL,
EXPLOITATION_ID CHAR(32) NOT NULL,
CONSTRAINT FK_OBJ FOREIGN KEY(OBJ_ID) REFERENCES OBJETS(OBJ_ID),
CONSTRAINT FK_FCT FOREIGN KEY(FCT_ID) REFERENCES FONCTIONNAIRES(FCT_ID),
CONSTRAINT FK_INFR FOREIGN KEY(INFR_ID) REFERENCES INFRACTIONS(INFR_ID),
CONSTRAINT FK_AINFR FOREIGN KEY(AINFR_ID) REFERENCES AUTREINFRACTIONS(AINFR_ID),
CONSTRAINT FK_EXPL FOREIGN KEY(EXPLOITATION_ID) REFERENCES EXPLOITATIONS(EXPLOITATION_ID)
);
CREATE TABLE VICTIMES(
TYPEVICT_ID CHAR(50) NOT NULL,
AFF_ID CHAR(50) NOT NULL,
VICT_ID INT PRIMARY KEY IDENTITY NOT NULL,
VICT_NOM CHAR(50),
VICT_PRENOM CHAR(50),
VICT_AUTRE CHAR(50),
VICT_ADRESSE CHAR(50),
CONSTRAINT FK_TYPE_VICT FOREIGN KEY(TYPEVICT_ID) REFERENCES TYPEVICTIMES(TYPEVICT_ID),
CONSTRAINT FK_AFF_ID FOREIGN KEY(AFF_ID) REFERENCES AFFAIRES(AFF_ID)
);

ALTER TABLE TYPEVICTIMES ADD CONSTRAINT CK_TYPEVICT_NOM CHECK (TYPEVICT_NOM IN('entreprise','association','particulair','administration'))

ALTER TABLE TYPEVICTIMES DROP CONSTRAINT CK_TYPEVICT_NOM
